### PR TITLE
Build setup; environment variable-based config

### PR DESCRIPTION
**Pull request by flotwig**
This PR:
- [x] Adds `build.sh`, which uses `cmake` and `make` to build all `.c` and `.h` files under `lib`
- [x] Adds `start.sh`, which supplies basic environment variables and launches `./bin/circ`
- [x] Adds `lib/config`, which reads in config variables from environment to C strings
- [x] Adds `lib/log`, with basic info- and debug-level logging statements
- [x] Updates `main.c` to print out the loaded config variables before exiting
- [x] Adds build instructions to README.md

My C-fu is weak, but this is better than nothing!

### CODE REVIEW

**Review by rkitover — CHANGES_REQUESTED** [review]
Pasting what I wrote on irc:

```
[02:52:41] <%Crocodillian> flotwig: why did you delete that
1. 
[02:53:10] <%Crocodillian> flotwig: also apparently you don't know how to use cmake, you make a build directory and you build there
2. 
[02:55:42] <%Crocodillian> flotwig: never use GLOB for sources in cmake
[02:55:55] <%Crocodillian> flotwig: they must be listed explicitly
3.
[02:56:38] <%Crocodillian> flotwig: in C the opening brace is always on its own line
[02:56:45] <%Crocodillian> flotwig: and C++ as well
[02:58:22] <%Crocodillian> we probably also want to use tabs
[02:58:31] <%Crocodillian> but that's not important
4. [02:59:28] <%Crocodillian> flotwig: also, your commit messages suck
[02:59:53] <%Crocodillian> flotwig: having said all that, thank you for working on this
[03:01:01] <%Crocodillian> flotwig: this is the definitive guide on git commit messages: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
```

Also please rewrite history to something more reasonable with `rebase -i`.

**Comment by flotwig** [comment]
Split up the log so I could respond to changes:

1. Nice - updated it to do exactly that. This is way better.
2. Hmm, I like the glob, I think it makes more sense to do it that way vs. updating the CMakeLists.txt for every new file. Is there a technical reason that we shouldn't?
3. Let's break away from C style and use braces on the same line, I think most people in `#gnulag` prefer it. I'd also be open to using an autoformatter on pre-commit or something, but that'd probably be a separate PR.
4. Fixed.

**Comment by rkitover** [comment]
Various reasons not to use GLOB see:

https://stackoverflow.com/questions/32411963/why-is-cmake-file-glob-evil

**Comment by flotwig** [comment]
Makes sense. Updated.

**Review by rkitover — APPROVED** [review]

**Pull request merged**
